name: publish-docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    if: >-
      github.actor != 'dependabot[bot]' &&
      github.actor != 'renovate[bot]' &&
      github.actor != 'renovate'
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Set cache identifier
        run: printf 'cache_id=%s\n' "$(date -u '+%V')" >> "$GITHUB_ENV"
      - name: Cache MkDocs assets
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install uv (with cache)
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install just
        uses: taiki-e/install-action@a2352fc6ce487f030a3aa709482d57823eadfb37 # 2.75.16
        with:
          tool: just
      - name: Deploy the documentation to GitHub Pages
        run: just doc-build
